###
GET http://localhost:8888/experiences/category
Accept: application/json

###
GET http://localhost:8888/experiences
Accept: application/json

###
GET http://localhost:8888/experiences/location/a166e450-a8a7-4b1e-b140-02b36370a1d6
Accept: application/json

###
POST http://localhost:8888/experiences
Content-Type: application/json

{
  "name": "Alpaca walks",
  "duration": 1,
  "locations": [
    {
      "name": "Munich",
      "timeslots": [
        {
          "name": "Mondays at 13:00",
          "price": {
            "name": "10EUR",
            "rate": 10
          }
        }
      ]
    },
    {
      "name": "Hamburg",
      "timeslots": [
        {
          "name": "Saturdays at 11:00",
          "price": {
            "name": "20EUR",
            "rate": 20
          }
        }
      ]
    }
  ]
}

###

POST http://localhost:8888/prices/assign-to-timeslot
Content-Type: application/json

{
  "name": "20EUR",
  "rate": 20,
  "timeslot": {
    "id": "274839e3-87a0-4452-a0bb-6b9715f68793"
  }
}

###
POST http://localhost:8888/vouchers
Content-Type: application/json

{
 "totalAmount": 45,
  "customer": {
    "name": "John Doe",
    "address": "Jose street 2332"
  },
  "appointment": {
    "experienceID": "274839e3-87a0-4452-a0bb-6b9715f68793",
    "locationID": "274839e3-87a0-4452-a0bb-6b9715f68793",
    "timeslotID": "274839e3-87a0-4452-a0bb-6b9715f68793"
  }

}

