###
GET http://localhost:8888/experiences/category
Accept: application/json

###
GET http://localhost:8888/experiences
Accept: application/json

###
GET http://localhost:8888/experiences/location/3d594ac7-1d3a-45b8-bbe9-2f8b8b089909
Accept: application/json

###
POST http://localhost:8888/experiences
Content-Type: application/json

{
  "name": "Alpaca walks",
  "duration": 1,
  "locations": [
    {
      "name": "Munich",
      "timeslots": [
        {
          "name": "Mondays at 13:00",
          "price": {
            "name": "10EUR",
            "rate": 10
          }
        }
      ]
    },
    {
      "name": "Hamburg",
      "timeslots": [
        {
          "name": "Saturdays at 11:00",
          "price": {
            "name": "20EUR",
            "rate": 20
          }
        }
      ]
    }
  ]
}

###

POST http://localhost:8888/prices/assign-to-timeslot
Content-Type: application/json

{
  "name": "20EUR",
  "rate": 20,
  "timeslot": {
    "id": "a4241912-bd9b-463d-9135-6184a4773cea"
  }
}
