GET http://localhost:8888/experiences/location
Accept: application/json

###
POST http://localhost:8888/experiences
Content-Type: application/json

{
  "name": "Flying",
  "locations": [
    {
      "name": "Berlin"
    }
  ]
}

###
